#pragma once
#include "VPU_roap.h"
#include "game_roap_blob.h"   // generated by bin2h from game.roap at the project root

// The ROAP baked into this executable at compile time -- the default way to
// ship a MISL game: one file, no external assets, no runtime dependency.
//
// Drop a game.roap next to the Makefile and the build bakes it in and defines
// game_roap here. Hand it to the VPU from your game():
//
//     #include "fuselage/fuselage.h"
//     #include "fuselage/ROAP/roap_embedded.h"
//     #include "fuselage/ROAP/roap.h"
//     #include "game.h"
//
//     void game(void) {
//         RoapPumpInput();      // publish this tick's input to the guest
//         VPU(&game_roap);      // spend one time-slice in the blob
//     }
//
// That is the whole tick: VPU() spends one time-slice, services the guest's
// ecalls, and returns. It is idempotent once the blob halts, so calling it
// unconditionally is safe.
//
// RoapPumpInput() is what puts keyboard/mouse/pad state in the MMIO page the
// guest reads (see roap.h). Leave it out and the guest still runs -- it just
// reads input frozen at whatever was last written, which looks like a game
// ignoring the controller rather than like a missing call.
//
// The alternative shipping mode is MISLlauncher -- a generic host that loads
// a .roap from disk at runtime instead of baking one in (see roap_launcher.h).
static const ROAP game_roap = {
    game_roap_code,           // raw RV32I bytes, from the generated blob header
    sizeof game_roap_code,    // size
    0,                        // entryPC -- blobs are linked flat at 0 (roap.ld)
};
